Gary/management UI
HackGT/registration2 pull request #101
Opened 2023-02-20 01:17 UTC by gary-peng

- Added a new modal on select events page to create hexathons.
- Visible to exec only.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/49541146/219987933-19acf1f9-225b-4347-8da4-618f9fa24ca2.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/49541146/219988011-542e32ab-a774-4665-b7a4-70bca4240e4d.png">

2023-02-22 01:35 UTC, Roshan-D requested changes

2023-02-22 01:35 UTC, Roshan-D commented on src/components/selectEvent/HexathonModal.tsx
> +                  <Input {...register("emailHeaderImage")} />
can you make this an image upload?

2023-02-22 01:35 UTC, Roshan-D commented on src/components/selectEvent/HexathonModal.tsx
> +                  <Input {...register("coverImage")} />
can you make this an image upload?

2023-02-22 01:35 UTC, Roshan-D commented on src/components/selectEvent/HexathonModal.tsx
> +      apiUrl(Service.HEXATHONS, `/hexathons`),
See [this comment](https://github.com/HackGT/api/issues/125#issuecomment-1439313671)

2023-02-27 01:18 UTC, gary-peng commented
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/49541146/221450602-82f1c0d6-cda5-48b5-bcac-66d5606e7ef4.png">
Changed the image fields to file upload.

2023-02-27 19:48 UTC, Roshan-D requested changes
- Could you now take everything in public/events and upload it to the bucket
- Have the actual hexathons in SelectEvent.tsx use the images stored in the cloud

2023-03-08 03:14 UTC, Roshan-D approved these changes
Dope!

2023-03-08 03:14 UTC, merged